const BAD_REQUEST_STATUS = 400;
const UNAUTHORIZED_STATUS = 401;
const NOT_FOUND_STATUS = 404;
const SERVER_ERROR_STATUS = 500;

export {
  BAD_REQUEST_STATUS,
  UNAUTHORIZED_STATUS,
  NOT_FOUND_STATUS,
  SERVER_ERROR_STATUS,
};
